import {
  IntroRenderer,
  VariablesRenderer,
  SyntaxeRenderer,
  OperateursRenderer,
  IORenderer,
  ConstantesRenderer,
  ExpressionsRenderer,
  ChainesRenderer,
  LogiqueBaseRenderer,
  ExemplesRenderer,
  ConditionSiRenderer,
  ConditionSinonRenderer,
  SinonSiRenderer,
  ConditionImbriqueeRenderer,
  OperateursLogiquesRenderer,
  SelonRenderer,
  SelonImbriqueeRenderer,
  ConditionsCombineesRenderer,
  SelonPlageRenderer,
  BoucleIntroRenderer,
  BouclePourRenderer,
  BouclePourPasRenderer,
  BoucleTantqueRenderer,
  BoucleRepeterRenderer,
  BoucleCompteurRenderer,
  BoucleImbriqueeRenderer,
  BoucleRechercheRenderer,
  BoucleValidationRenderer,
  TableauRenderer,
  TableauInitRenderer,
  TableauParcoursRenderer,
  TableauSommeRenderer,
  TableauMaxMinRenderer,
  TableauRechercheRenderer,
  TableauInsertionRenderer,
  TableauCopieRenderer,
  TableauTriRenderer,
  TriSelectionRenderer,
  TriInsertionRenderer,
  TableauInverseRenderer,
  TableauDecalageRenderer,
  MatriceRenderer,
  MatriceInitRenderer,
  MatriceParcoursRenderer,
  MatriceSommeRenderer,
  MatriceDiagonaleRenderer,
  MatriceLigneColRenderer,
  MatriceMaxRenderer,
  MatriceSymetrieRenderer,
  MatriceTransposeeRenderer,
  MatriceInverseRenderer,
  MatriceDecalageRenderer,
  StructRenderer,
  StructChampsRenderer,
  StructModificationRenderer,
  StructAffichageRenderer,
  StructTableauRenderer,
  StructRechercheRenderer,
  StructComparaisonRenderer,
  StructComplexeRenderer,
  AdvancedDecompositionRenderer,
  AdvancedDataFlowRenderer,
  AdvancedDebugRenderer,
  AdvancedMiniProjectRenderer,
  AdvancedReviewRenderer,
  ExerciceRenderer,
  ChallengeRenderer,
  GenericRenderer,
} from './components/renderers';

export {
  IntroRenderer,
  VariablesRenderer,
  SyntaxeRenderer,
  OperateursRenderer,
  IORenderer,
  ConstantesRenderer,
  ExpressionsRenderer,
  ChainesRenderer,
  LogiqueBaseRenderer,
  ExemplesRenderer,
  ConditionSiRenderer,
  ConditionSinonRenderer,
  SinonSiRenderer,
  ConditionImbriqueeRenderer,
  OperateursLogiquesRenderer,
  SelonRenderer,
  SelonImbriqueeRenderer,
  ConditionsCombineesRenderer,
  SelonPlageRenderer,
  BoucleIntroRenderer,
  BouclePourRenderer,
  BouclePourPasRenderer,
  BoucleTantqueRenderer,
  BoucleRepeterRenderer,
  BoucleCompteurRenderer,
  BoucleImbriqueeRenderer,
  BoucleRechercheRenderer,
  BoucleValidationRenderer,
  TableauRenderer,
  TableauInitRenderer,
  TableauParcoursRenderer,
  TableauSommeRenderer,
  TableauMaxMinRenderer,
  TableauRechercheRenderer,
  TableauInsertionRenderer,
  TableauCopieRenderer,
  TableauTriRenderer,
  TriSelectionRenderer,
  TriInsertionRenderer,
  TableauInverseRenderer,
  TableauDecalageRenderer,
  MatriceRenderer,
  MatriceInitRenderer,
  MatriceParcoursRenderer,
  MatriceSommeRenderer,
  MatriceDiagonaleRenderer,
  MatriceLigneColRenderer,
  MatriceMaxRenderer,
  MatriceSymetrieRenderer,
  MatriceTransposeeRenderer,
  MatriceInverseRenderer,
  MatriceDecalageRenderer,
  StructRenderer,
  StructChampsRenderer,
  StructModificationRenderer,
  StructAffichageRenderer,
  StructTableauRenderer,
  StructRechercheRenderer,
  StructComparaisonRenderer,
  StructComplexeRenderer,
  AdvancedDecompositionRenderer,
  AdvancedDataFlowRenderer,
  AdvancedDebugRenderer,
  AdvancedMiniProjectRenderer,
  AdvancedReviewRenderer,
  ExerciceRenderer,
  ChallengeRenderer,
  GenericRenderer,
};

//  Dispatch map
// eslint-disable-next-line react-refresh/only-export-components
export const LESSON_RENDERERS = {
  // Niveau 1
  intro: IntroRenderer,
  variables: VariablesRenderer,
  syntaxe: SyntaxeRenderer,
  operateurs: OperateursRenderer,
  io: IORenderer,
  constantes: ConstantesRenderer,
  expressions: ExpressionsRenderer,
  chaines: ChainesRenderer,
  logique_base: LogiqueBaseRenderer,
  exemples: ExemplesRenderer,
  // Niveau 2
  condition_si: ConditionSiRenderer,
  condition_sinon: ConditionSinonRenderer,
  sinon_si: SinonSiRenderer,
  condition_imbrique: ConditionImbriqueeRenderer,
  operateurs_logiques: OperateursLogiquesRenderer,
  selon: SelonRenderer,
  selon_imbrique: SelonImbriqueeRenderer,
  conditions_combinees: ConditionsCombineesRenderer,
  selon_plage: SelonPlageRenderer,
  // Niveau 3
  boucle_intro: BoucleIntroRenderer,
  boucle_pour: BouclePourRenderer,
  boucle_pour_pas: BouclePourPasRenderer,
  boucle_tantque: BoucleTantqueRenderer,
  boucle_repeter: BoucleRepeterRenderer,
  boucle_compteur: BoucleCompteurRenderer,
  boucle_imbrique: BoucleImbriqueeRenderer,
  boucle_recherche: BoucleRechercheRenderer,
  boucle_validation: BoucleValidationRenderer,
  // Niveau 4
  tableau: TableauRenderer,
  tableau_init: TableauInitRenderer,
  tableau_parcours: TableauParcoursRenderer,
  tableau_somme: TableauSommeRenderer,
  tableau_max_min: TableauMaxMinRenderer,
  tableau_recherche: TableauRechercheRenderer,
  tableau_insertion: TableauInsertionRenderer,
  tableau_copie: TableauCopieRenderer,
  tableau_tri: TableauTriRenderer,
  tri_selection: TriSelectionRenderer,
  tri_insertion: TriInsertionRenderer,
  tableau_inverse: TableauInverseRenderer,
  tableau_decalage: TableauDecalageRenderer,
  // Niveau 5
  matrice: MatriceRenderer,
  matrice_init: MatriceInitRenderer,
  matrice_parcours: MatriceParcoursRenderer,
  matrice_somme: MatriceSommeRenderer,
  matrice_diagonale: MatriceDiagonaleRenderer,
  matrice_ligne_col: MatriceLigneColRenderer,
  matrice_max: MatriceMaxRenderer,
  matrice_symetrie: MatriceSymetrieRenderer,
  matrice_transposee: MatriceTransposeeRenderer,
  matrice_inverse: MatriceInverseRenderer,
  matrice_decalage: MatriceDecalageRenderer,
  // Niveau 6
  struct: StructRenderer,
  struct_champs: StructChampsRenderer,
  struct_modification: StructModificationRenderer,
  struct_affichage: StructAffichageRenderer,
  struct_tableau: StructTableauRenderer,
  struct_recherche: StructRechercheRenderer,
  struct_comparaison: StructComparaisonRenderer,
  struct_complexe: StructComplexeRenderer,
  // Niveau 7
  advanced_decomposition: AdvancedDecompositionRenderer,
  advanced_data_flow: AdvancedDataFlowRenderer,
  advanced_debug: AdvancedDebugRenderer,
  advanced_mini_project: AdvancedMiniProjectRenderer,
  advanced_review: AdvancedReviewRenderer,
  // Exercice
  exercice: ExerciceRenderer,
  challenge: ChallengeRenderer,
};
